development:
  adapter: postgresql
  host: localhost
  database: wolf_development
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  host: localhost
  database: wolf_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  database: wolf
  pool: 5
  timeout: 5000

cucumber:
  <<: *test